services:
  - type: web
    name: canavar-downloader
    env: python
    # Burada hem k端t端phaneleri y端kl端yoruz hem FFmpeg'i kontrol ediyoruz
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0